import { SettingSchemaDesc } from '@logseq/libs/dist/LSPlugin'

export const settingsSchema: SettingSchemaDesc[] = [
  {
    key: 'todoTriggerTags',
    type: 'string',
    default: '#todo, #task',
    title: 'Todo Trigger Tags',
    description: 'Comma-separated tags that trigger todo creation (e.g., #todo, #task)',
  },
  {
    key: 'defaultTranscriptionMode',
    type: 'enum',
    default: 'literal',
    enumChoices: ['literal', 'ai'],
    enumPicker: 'select',
    title: 'Default Transcription Mode',
    description: 'Default mode for processing voice notes',
  },
  {
    key: 'hierarchicalTasks',
    type: 'boolean',
    default: true,
    title: 'Create Hierarchical Tasks',
    description: 'Create master task with subtasks when using AI mode',
  },
  {
    key: 'defaultProject',
    type: 'string',
    default: '',
    title: 'Default Todoist Project',
    description: 'Default project ID for tasks (leave empty to use inbox)',
  },
  {
    key: 'projectMappings',
    type: 'object',
    default: {},
    title: 'Project Tag Mappings',
    description: 'Map hashtags to Todoist projects (configure in JSON format)',
  },
  {
    key: 'aiPrompt',
    type: 'string',
    default: '',
    title: 'Custom AI Prompt',
    description: 'Custom prompt for AI task extraction (leave empty for default)',
  },
  {
    key: 'createTranscriptionPage',
    type: 'boolean',
    default: true,
    title: 'Create Transcription Page',
    description: 'Create a new page with transcription and AI summary for each voice note',
  },
  {
    key: 'addTasksSection',
    type: 'boolean',
    default: true,
    title: 'Add Tasks Section to Page',
    description: 'Add a Tasks section to the created transcription page',
  },
  {
    key: 'pageTemplate',
    type: 'string',
    default: '',
    title: 'Page Template Name',
    description: 'Optional template to use for created pages (leave empty for default structure)',
  },
  {
    key: 'voiceFlowShortcut',
    type: 'string',
    default: 'mod+shift+v',
    title: 'Keyboard Shortcut',
    description: 'Keyboard shortcut for VoiceFlowAutomate command',
  },
  {
    key: 'autoDeleteProcessedAudio',
    type: 'boolean',
    default: false,
    title: 'Auto-delete Processed Audio',
    description: 'Automatically remove audio file reference after processing',
  },
  {
    key: 'appendTranscriptionTimestamp',
    type: 'boolean',
    default: true,
    title: 'Append Timestamp',
    description: 'Add timestamp to transcription results',
  },
  {
    key: 'autoOpenCreatedPage',
    type: 'boolean',
    default: false,
    title: 'Auto-open Created Page',
    description: 'Automatically open the created transcription page after processing',
  },
  {
    key: 'debugMode',
    type: 'boolean',
    default: false,
    title: 'Debug Mode',
    description: 'Enable detailed logging for troubleshooting',
  }
]